### PR TITLE
Makefile: Add -U_FORTIFY_SOURCE to disable memcpy checks

### PR DESCRIPTION
**Pull request by shawnanastasio**
On some toolchains, GCC will insert bounds checks in memcpy and friends
by default which erroneously trip in main() as it loads the contents
of flash into ram.

Passing -U_FORTIFY_SOURCE to GCC prevents these checks from being
emitted and fixes the issue.

### CODE REVIEW

**Comment by kbeckmann** [comment]
Thanks for raising this. Upon investigating this it is caused by the memcpy in main.c:276. This memcpy does some "magic" where we copy from flash to raw ram using symbols exposed to use from the ld script. These are false positives, however it would be nice to be able to run with fortify on. I'll push a workaround for this.

**Comment by shawnanastasio** [comment]
I don't think your workaround is correct - looking at my compiled binary it seems GCC has optimized your custom `memcpy_no_check` call into a normal `memcpy`.  The best way to avoid this is probably to put `memcpy_no_check` in its own .c file that contains `#undef _FORTIFY_SOURCE` at the top before it includes `string.h`.

**Comment by shawnanastasio** [comment]
Hmm, even though it's being optimized into a memcpy, the bounds check doesn't seem to get invoked so it works fine on my G&W.  I guess no further action is needed, then.

**Comment by kbeckmann** [comment]
Maybe it got merged with the inner memcpy implementation? I.e. not __memcpy_ichk or whatever it is called.

**Comment by shawnanastasio** [comment]
Ah yes, that seems to be what's happening. So I guess its working by accident - gcc isn't using the custom memcpy implementation but it optimizes it into a branch to the normal `memcpy` and not `__memcpy_chk` so the bounds check is still bypassed. I have a patch that implements my idea of moving `memcpy_no_check` into a separate .c file with _FORTIFY_SOURCE undef'd that I can submit if you want, but otherwise I guess the current solution works fine.

**Comment by kbeckmann** [comment]
It would be interesting to understand what is going on. I don't see this behaviour in my build (arm-none-eabi-gcc 10.2.0). I mean my code is custom code, it doesn't reference `memcpy` at all, so gcc should not touch it imho. If it does, that seems like a bug.

**Comment by shawnanastasio** [comment]
Here's the excerpt from objdump:
```
8001422:	f7ff fa79 	bl	8000918 <OSPI_EnableMemoryMappedMode>
 8001426:	4814      	ldr	r0, [pc, #80]	; (8001478 <main+0x51c>)
 8001428:	4a14      	ldr	r2, [pc, #80]	; (800147c <main+0x520>)
 800142a:	4290      	cmp	r0, r2
 800142c:	d003      	beq.n	8001436 <main+0x4da>
 800142e:	1a12      	subs	r2, r2, r0
 8001430:	4913      	ldr	r1, [pc, #76]	; (8001480 <main+0x524>)
 8001432:	f00b f92f 	bl	800c694 <memcpy>
```



> I mean my code is custom code, it doesn't reference `memcpy` at all, so gcc should not touch it imho. If it does, that seems like a bug.

GCC will look for code that looks like memcpy and try to optimize it into a call to the actual memcpy implementation, this is well documented behavior: https://stackoverflow.com/questions/57539509/how-do-i-stop-gcc-from-optimizing-this-byte-for-byte-copy-into-a-memcpy-call. There are also some flags mentioned in that post that force GCC to disable the behavior, but that shouldn't be necessary since it's emitting branches to the non-checked version anyways.

**Comment by kbeckmann** [comment]
Yeah, but that's all good if it's the same code. My point (that I didn't express that well) is that it shouldn't change the behaviour of my code. It's ok if it reuses memcpy, as long as it doesn't change the behaviour and causes side effects that I didn't have in my code :). So I think what it does here is fine and correct.

**Comment by shawnanastasio** [comment]
Oh, I see what you mean. Yeah I think you're right about that, since your memcpy implementation doesn't do checks it should be reasonable to assume that whatever GCC optimizes it into will also not have any checks (barring bugs, of course :)

**Pull request closed without merging**
