### PR TITLE
Parse roms refactor

### PR DESCRIPTION
**Pull request by BrianPugh**
Main things:

- uses `pathlib.Path` instead of `os.path`
- No longer shells out to split/gsplit
- Adds easy future expandability for different compression algorithms
- attempts to use python's lz4. If unavailable, fallsback to shelling it out
- change all `subprocess.run` to `subprocess.check_output`

I tested this on 34 GB/GBC and 31 NES games and the files produces by the python `lz4` bindings are identical to the files produces by the lz4 CLI.

Current drawbacks:

- Due to the restructuring, if python `lz4` isn't installed, then each individual gameboy bank is being shelled out to `lz4`, which is significantly slower when compared to passing all the banks into a single `lz4` command. Across those 34 GB/GBC games, this takes ~35s (as opposed to near-instantaneous). If we feel like this is too long, I can make a workaround, but then the code will be less clean

### CODE REVIEW

**Comment by kbeckmann** [comment]
Thanks. Please test with one rom for each supported system. There seems to be a few parameters missing when building for e.g. gg and sms. I'm getting the following callstack when building a gg rom:

```
Traceback (most recent call last):
  File "/home/konrad/dev/game-and-watch-retro-go/parse_roms.py", line 606, in <module>
    ROMParser().parse(args)
  File "/home/konrad/dev/game-and-watch-retro-go/parse_roms.py", line 508, in parse
    save_size, rom_size = self.generate_system(
  File "/home/konrad/dev/game-and-watch-retro-go/parse_roms.py", line 401, in generate_system
    self._compress_rom(
  File "/home/konrad/dev/game-and-watch-retro-go/parse_roms.py", line 298, in _compress_rom
    raise ValueError(f'Unknown compression method: "{compress}"')
ValueError: Unknown compression method: "None"
```

**Comment by BrianPugh** [comment]
sorry about that, just fixed.

**Comment by BrianPugh** [comment]
If you want to hold off a day or two on this, I can test it end to end on hardware.

**Comment by BrianPugh** [comment]
If you want to hold off a day or two on this, I can test it end to end on hardware.

**Comment by kbeckmann** [comment]
Sure, there's no rush on my end. 

What do you say if we only commit the configuration in #96, then this PR should apply cleanly plus that you can run the rules on the new code?

**Comment by BrianPugh** [comment]
Sounds like a good plan!

**Comment by BrianPugh** [comment]
so I ran this end to end with a gb, nes, and gg game and everything seems fine.

**Comment by kbeckmann** [comment]
Thanks!

**Pull request merged**
