### PR TITLE
Added a watchdog to avoid power-cycles when things go wrong

### PR DESCRIPTION
**Pull request by jan2642**
This should solve issue #45

### CODE REVIEW

**Comment by jan2642** [comment]
The order of lines in gw_retrogo.ioc changed a lot by CubeMX. When sorting the old and new files and doing a diff, these are the actual changes:

+Mcu.IP12=WWDG1
-Mcu.IPNb=12
+Mcu.IPNb=13
+Mcu.Pin58=VP_WWDG1_VS_WWDG
-Mcu.PinsNb=58
+Mcu.PinsNb=59
-MxCube.Version=6.1.0
+MxCube.Version=6.1.1
+NVIC.WWDG_IRQn=true\:0\:0\:false\:false\:true\:true\:true
-ProjectManager.functionlistsort=1-MX_GPIO_Init-GPIO-false-HAL-true,2-MX_DMA_Init-DMA-false-HAL-true,3-SystemClock_Config-RCC-false-HAL-false,4-MX_LTDC_Init-LTDC-false-HAL-true,5-MX_SPI2_Init-SPI2-false-HAL-true,6-MX_OCTOSPI1_Init-OCTOSPI1-false-HAL-true,7-MX_SAI1_Init-SAI1-false-HAL-true,8-MX_RTC_Init-RTC-false-HAL-true,0-MX_CORTEX_M7_Init-CORTEX_M7-false-HAL-true
+ProjectManager.functionlistsort=1-MX_GPIO_Init-GPIO-false-HAL-true,2-MX_DMA_Init-DMA-false-HAL-true,3-SystemClock_Config-RCC-false-HAL-false,4-MX_LTDC_Init-LTDC-false-HAL-true,5-MX_SPI2_Init-SPI2-false-HAL-true,6-MX_OCTOSPI1_Init-OCTOSPI1-false-HAL-true,7-MX_SAI1_Init-SAI1-false-HAL-true,8-MX_RTC_Init-RTC-false-HAL-true,9-MX_DAC1_Init-DAC1-false-HAL-true,10-MX_DAC2_Init-DAC2-false-HAL-true,0-MX_CORTEX_M7_Init-CORTEX_M7-false-HAL-true
+VP_WWDG1_VS_WWDG.Mode=WWDG_Activate
+VP_WWDG1_VS_WWDG.Signal=WWDG1_VS_WWDG
+WWDG1.Counter=127
+WWDG1.EWIMode=WWDG_EWI_ENABLE
+WWDG1.IPParameters=Prescaler,Window,Counter,EWIMode
+WWDG1.Prescaler=WWDG_PRESCALER_32
+WWDG1.Window=127

**Comment by kbeckmann** [comment]
Thanks a lot for this! Did you measure how long the watchdog timeout is in ms?

**Comment by jan2642** [comment]
> Thanks a lot for this! Did you measure how long the watchdog timeout is in ms?

Unfortunately I don't have the right tools, but according to the documentation it should be
(1/140,000) * 4096 * 128 * (127 - 64 + 1) = 239,6 ms

**Comment by kbeckmann** [comment]
Ok! Should be fine. Some games may have some heavy transitions that take multiple 10s of ms to load before we end up in the main loop again, e.g. smb3. But a 200+ms budget should be alright.

**Comment by jan2642** [comment]
It's the largest possible timeout with the WWDG without lowering the APB clocks.
The IWDG can use much longer timeouts as it uses the 32 kHz clock source but I selected the WWDG because it has an EarlyWarning interrupt. That way it can be caught during debugging sessions to see what was happening when the watchdog is about to fire.

**Comment by kbeckmann** [comment]
I see. Yeah the early warning is good. I added some code there now if you check the latest main. It will set the boot_magic and then we will do a BSOD. Also moved the log to the persistent section so we can print the old log.

**Pull request merged**
