### PR TITLE
Update Makefile.common

### PR DESCRIPTION
**Pull request by amix307**
Added a custom variable to add support for different flash sizes

### CODE REVIEW

**Comment by kbeckmann** [comment]
Thanks for the PR. This will however only solve a part of the problem; 64MB memory like the one people are using (MX25U51245GZ4I00) requires changes to the commands and addressing mode as well.

The ideal way to solve this is by probing the flash and then selecting the appropriate configuration during boot. Another is to have different configurations that can be selected when building.

**Comment by amix307** [comment]
> Thanks for the PR. This will however only solve a part of the problem; 64MB memory like the one people are using (MX25U51245GZ4I00) requires changes to the commands and addressing mode as well.
> 
> The ideal way to solve this is by probing the flash and then selecting the appropriate configuration during boot. Another is to have different configurations that can be selected when building.

I understand. I just bought 64MB flash and will wait it in next 2 weeks.

**Comment by kbeckmann** [comment]
Until we get a proper solution for this you may refer to [this](https://gist.github.com/DNA64/1b3aa3ef14378cb5bb6fdff0411e17c3) in the meanwhile.

**Comment by BrianPugh** [comment]
so what are the main challenges for "official" support on this? Are they (either or):
1. We want this to be automatic based on detected SPI flash size
2. `game-and-watch-flashloader` also requires some modifications in tandem.

**Comment by kbeckmann** [comment]
Yeah, both.

We should start with reading the JEDEC ID and size, then based on that, select appropriate commands and select 24/32 bit addressing mode.

**Comment by kbeckmann** [comment]
I'm closing this PR since we will need to rewrite the flash driver quite a bit. I'll be working on this.

The branch [flashapp](https://github.com/kbeckmann/game-and-watch-retro-go/tree/flashapp) removes the dependency on flashloader, so we won't need to keep the both implementations in sync.

**Pull request closed without merging**
